#!/bin/bash
# AI手札 — 部署脚本 (Step 5)
# Git commit + push 到 GitHub Pages

set -e

TARGET_DATE="${1:-$(date +%Y-%m-%d)}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "部署开始 - $TARGET_DATE"
cd "$ROOT"

if git diff --quiet && git diff --cached --quiet; then
    echo "没有检测到变更，跳过部署"
    exit 0
fi

git add public/
git add data/daily-workflow/"$TARGET_DATE"/

git commit -m "daily: ${TARGET_DATE} 日报更新

- 新增日报: ${TARGET_DATE}
- 更新主页日历和统计数据
- Auto-generated by AI手札 orchestrator"

echo "Git commit 完成"

if command -v jq &> /dev/null; then
    AUTO_PUSH=$(jq -r '.deploy.auto_push' "$ROOT/config/settings.json")
else
    AUTO_PUSH="true"
fi

if [ "$AUTO_PUSH" = "true" ]; then
    BRANCH=$(jq -r '.deploy.branch // "main"' "$ROOT/config/settings.json" 2>/dev/null || echo "main")
    echo "推送到 origin/$BRANCH..."
    git push origin "$BRANCH"
    echo "推送完成"
else
    echo "auto_push 未启用，跳过推送"
fi

echo "部署完成!"
